name: Deploy

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] 

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
